#!/bin/bash

# Run tests with phantom.js.
# It's possible to customize ouput a bit, e.g.:
# ./run my-test.js --show-colors=false --show-page-console=true --show-passed-tests=true

_DIR=`dirname $0`

[ "$PHANTOMJS" ] || PHANTOMJS=`which phantomjs`

if ! [ "$PHANTOMJS" ]; then
    [ -e $_DIR/.phantomjs ] || $_DIR/install.sh
    PHANTOMJS=$_DIR/.phantomjs/bin/phantomjs
fi

"$PHANTOMJS" $_DIR/test-runner.coffee --working-directory=`pwd` $*
